---

- hosts: all
  gather_facts: false
  vars:
    num_messages: 50
  tasks:
    - debug:
        name: "debug1"
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
    - debug: 
        name: "debug2"
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
    - debug: 
        name: "debug3"
        msg: "This is a debug message: {{ item }}"
      with_sequence: 'count={{ num_messages }}'
