- name: Attempt to add a Tower team to a non-existant Organization
  tower_team:
    name: Test Team
    organization: Missing Organization
    state: present
  register: result
  ignore_errors: yes

- name: Assert a meaningful error was provided for the failed Tower team creation
  assert:
    that:
      - result is failed
      - "'The organizations Missing Organization was not found on the Tower server' in result.msg"

- name: Create a Tower team
  tower_team:
    name: Test Team
    organization: Default
  register: result

- assert:
    that:
      - "result is changed"

- name: Delete a Tower team
  tower_team:
    name: Test Team
    organization: Default
    state: absent
  register: result

- assert:
    that:
      - "result is changed"

- name: Check module fails with correct msg
  tower_team:
    name: Test Team
    organization: Non Existing Org
    state: present
  register: result
  ignore_errors: true

- assert:
    that:
      - "'The organizations Non Existing Org was not found on the Tower server' in result.msg"
