---
- name: Create a credential in check mode
  tower_credential_type:
    name: "My Custom Cred"
    description: "This is a custom credential"
    kind: "cloud"
    #inputs: ""
    #injectors:
    state: present
  check_mode: True
  register: result

- assert:
    that:
      - result is changed

- name: "Make sure we can't delete the credential made in check mode"
  tower_credential_type:
    name: "My Custom Cred"
    state: absent
  register: result
  ignore_errors: True

- assert:
    that:
      - result is not changed
      - result is not failed

- name: Add Tower credential type
  tower_credential_type:
    description: Credential type for Test
    name: test-credential-type
    kind: cloud
    inputs: {"fields": [{"type": "string", "id": "username", "label": "Username"}, {"secret": True, "type": "string", "id": "password", "label": "Password"}], "required": ["username", "password"]}
    injectors: {"extra_vars": {"test": "foo"}}
  register: result

- assert:
    that:
      - "result is changed"

- name: Remove a Tower credential type
  tower_credential_type:
    name: test-credential-type
    state: absent
  register: result

- assert:
    that:
      - "result is changed"
